#!/bin/bash

# Function to remove inbound and outbound rules referencing a specific source security group
remove_rules_and_delete_sg() {
    local security_group_id=$1
#    local source_security_group_id=$2
    local source_security_group_id=$(aws ec2 describe-security-groups --group-id "$security_group_id" | jq -r '.SecurityGroups[].IpPermissions[].UserIdGroupPairs[].GroupId')
    local destination_security_group_id=$(aws ec2 describe-security-groups --group-id "$security_group_id" | jq -r '.SecurityGroups[].IpPermissionsEgress[].UserIdGroupPairs[].GroupId')
    echo "Removing inbound rule referencing source security group $source_security_group_id..."
    aws ec2 revoke-security-group-ingress --group-id "$security_group_id" --protocol all --port all --source-group "$source_security_group_id"
    aws ec2 revoke-security-group-ingress --group-id "$security_group_id" --protocol all --port all --source-group "$destination_security_group_id"
    echo "Removing outbound rule referencing source security group $source_security_group_id..."
    aws ec2 revoke-security-group-egress --group-id "$security_group_id" --protocol all --port all --source-group "$source_security_group_id"
    aws ec2 revoke-security-group-egress --group-id "$security_group_id" --protocol all --port all --source-group "$destination_security_group_id"

    local port="2049"
    echo "Removing inbound rule referencing source security group $source_security_group_id..."
    aws ec2 revoke-security-group-ingress --group-id "$security_group_id" --protocol tcp --port $port --source-group "$source_security_group_id"
    aws ec2 revoke-security-group-ingress --group-id "$security_group_id" --protocol tcp --port $port --source-group "$destination_security_group_id"
    echo "Removing outbound rule referencing source security group $source_security_group_id..."
    aws ec2 revoke-security-group-egress --group-id "$security_group_id" --protocol tcp --port $port --source-group "$source_security_group_id"
    aws ec2 revoke-security-group-egress --group-id "$security_group_id" --protocol tcp --port $port --source-group "$destination_security_group_id"


    echo "Deleting security group $security_group_id..."
    aws ec2 delete-security-group --group-id "$security_group_id"
}

# Main script

# Check if a security group ID is provided as an argument
if [ $# -ne 1 ]; then
    echo "Usage: $0 <security_group_id>"
    exit 1
fi

# Extract the security group ID and source security group ID from the arguments
security_group_id=$1
# source_security_group_id=$(aws ec2 describe-security-groups --group-id "$security_group_id" | jq -r '.SecurityGroups[].IpPermissions[].UserIdGroupPairs[].GroupId')

# Call the function to remove rules referencing the source security group and delete the security group
remove_rules_and_delete_sg "$security_group_id"
